name = "monedas-momentos-de-color"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
NEXT_PUBLIC_APP_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "monedas-momentos-db"
database_id = "535be7d8-3b8b-4e6c-b3bb-074a7cc75e09"
